name: "Setup kubectl"
description: "Installs kubectl and configures the Kubernetes context"
inputs:
  kube_api_server:
    description: 'Kubernetes API server URL'
    required: true
  kube_token:
    description: 'Kubernetes Token'
    required: true
  kube_ca:
    description: 'Kubernetes CA certificate'
    required: true
  kube_namespace:
    description: 'Kubernetes namespace'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: "latest"

    - name: Configure Kubernetes context
      shell: bash
      run: |
        echo "${{ inputs.kube_ca }}" | base64 --decode > /tmp/ca.crt
        kubectl config set-cluster igoryusha22-cluster --server="${{ inputs.kube_api_server }}" --certificate-authority=/tmp/ca.crt
        kubectl config set-credentials deployer --token="$(echo "${{ inputs.kube_token }}" | base64 --decode)"
        kubectl config set-context deploy-context --cluster=igoryusha22-cluster --user=deployer --namespace="${{ inputs.kube_namespace }}"
        kubectl config use-context deploy-context
