name: "Setup kubectl"
description: "Installs kubectl and configures the Kubernetes context"
inputs:
  kube_api_server:
    description: 'Kubernetes API server URL'
    required: true
  kube_token:
    description: 'Kubernetes Token'
    required: true
  kube_ca:
    description: 'Kubernetes CA certificate'
    required: true
  kube_namespace:
    description: 'Kubernetes namespace'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: "latest"

    - name: Debug Environment Variables
      run: |
        echo "KUBE API SERVER: $(echo "${INPUT_KUBE_API_SERVER}" | base64 --decode | head -c 11)"
        echo "KUBE TOKEN: $(echo "${INPUT_KUBE_TOKEN}" | base64 --decode | head -c 10)"
        echo "KUBE CA: $(echo "${INPUT_KUBE_CA}" | base64 --decode | head -c 10)"
      shell: bash

    - name: Configure Kubernetes context
      shell: bash
      run: |
        echo "${INPUT_KUBE_CA}" | base64 --decode > /tmp/ca.crt
        kubectl config set-cluster igoryusha22-cluster --server="${INPUT_KUBE_API_SERVER}" --certificate-authority="/tmp/ca.crt"
        kubectl config set-credentials deployer --token=$(echo "${INPUT_KUBE_TOKEN}" | base64 --decode)
        kubectl config set-context deploy-context --cluster=igoryusha22-cluster --user=deployer --namespace="${INPUT_KUBE_NAMESPACE}"
        kubectl config use-context deploy-context
        kubectl config view --minify
