name: CI-CD

on:
  push:
    branches:
      - main
  pull_request:

env:
  CI_COMMIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
  CI_REGISTRY: ${{ secrets.REGISTRY }}
  CI_REGISTRY_IMAGE: ${{ secrets.REGISTRY_IMAGE }}
  CI_REGISTRY_USER: ${{ secrets.REGISTRY_USERNAME }}
  CI_REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: ./.github/actions/node

      - name: Run ESLint
        run: npm run lint

  type-check:
    name: TypeScript Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: ./.github/actions/node

      - name: Run TypeScript validation
        run: npm run type-check

  nextjs-build-and-push:
    name: Build Next.js Image And Push To Registry
    runs-on: ubuntu-latest
    needs: [lint, type-check]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: ./.github/actions/docker

      - name: Build and Tag Next.js Image
        run: |
          make build \
            image="nextjs" \
            dockerfile="./docker/nextjs/Dockerfile" \
            BUILD="$(echo $CI_COMMIT_SHA | cut -c1-8)" \
            .

      - name: Push Next.js Image To Registry
        run: |
          make registry \
            image="nextjs" \
            BUILD="$(echo $CI_COMMIT_SHA | cut -c1-8)" \
            .

  nginx-build-and-push:
    name: Build Nginx Image And Push To Registry
    runs-on: ubuntu-latest
    needs: [lint, type-check]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: ./.github/actions/docker

      - name: Build and Tag Nginx Image
        run: |
          make build \
            image="nginx" \
            dockerfile="./docker/nginx/Dockerfile" \
            BUILD="$(echo $CI_COMMIT_SHA | cut -c1-8)" \
            .

      - name: Push Nginx Image To Registry
        run: |
          make registry \
            image="nginx" \
            BUILD="$(echo $CI_COMMIT_SHA | cut -c1-8)" \
            .

  nextjs-deploy:
    name: Deploy Next.js
    runs-on: ubuntu-latest
    needs: [nextjs-build-and-push]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup kubectl
        uses: ./.github/actions/kube
        with:
          kube_api_server: ${{ secrets.KUBE_API_SERVER }}
          kube_token: ${{ secrets.KUBE_TOKEN }}
          kube_ca: ${{ secrets.KUBE_CA }}

      - name: Setup Docker
        uses: ./.github/actions/docker

      - name: Deploy
        run: |
          make deploy \
            image="nextjs" \
            tag="latest" \
            BUILD="$(echo $CI_COMMIT_SHA | cut -c1-8)" \
            deployment="nextjs"

  nginx-deploy:
    name: Deploy Nginx
    runs-on: ubuntu-latest
    needs: [nginx-build-and-push]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup kubectl
        uses: ./.github/actions/kube
        with:
          kube_api_server: ${{ secrets.KUBE_API_SERVER }}
          kube_token: ${{ secrets.KUBE_TOKEN }}
          kube_ca: ${{ secrets.KUBE_CA }}

      - name: Setup Docker
        uses: ./.github/actions/docker

      - name: Deploy
        run: |
          make deploy \
            image="nginx" \
            tag="latest" \
            BUILD="$(echo $CI_COMMIT_SHA | cut -c1-8)" \
            deployment="nginx"
